# Note that nextauthjs/next-auth-example syncs from the v4 branch

nextauthjs/sveltekit-auth-example:
  - source: apps/examples/sveltekit
    dest: .
  - .github/FUNDING.yml
  - LICENSE

nextauthjs/solid-start-auth-example:
  - source: "apps/examples/solid-start"
    dest: .
  - .github/FUNDING.yml
  - LICENSE

nextauthjs/next-auth-gatsby-example:
  - source: apps/playgrounds/gatsby
    dest: .
  - .github/FUNDING.yml
  - LICENSE
